<?php

namespace RingCoin\AppBundle\Repository;

/**
 * TransactionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionsRepository extends \Doctrine\ORM\EntityRepository
{
}
