<?php

namespace RingCoin\AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllUsersOfYear(\DateTime $start, \DateTime $end){
        $qb = $this->createQueryBuilder('u')
            ->from($this->_entityName, 'u')
            ->where('u.dateInscription BETWEEN :start AND :end')
            ->setParameters(array('start'=>$start, 'end'=>$end));

        $users = $qb->getMaxResults();
        $data = [];

       /* foreach ($users as $user){
            if (!array_key_exists($user->getDateInscription(), $data)){
                $data[$user->getDateInscription()] = 0;
            }else{
                $data[$user->getDateInscription()] ++;
            }
        }*/

        return $data;
    }

}
