imports:
    - { resource: app_parameters.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    logo: '%kernel.project_dir%/web/bundles/ringcoinapp/img/ringcoin.png'
    fbk: '%kernel.project_dir%/web/bundles/ringcoinapp/img/fbk.png'
    reddit: '%kernel.project_dir%/web/bundles/ringcoinapp/img/reddit.png'
    youtube: '%kernel.project_dir%/web/bundles/ringcoinapp/img/youtube.png'
    btctalk: '%kernel.project_dir%/web/bundles/ringcoinapp/img/btctalk.png'
    twitter: '%kernel.project_dir%/web/bundles/ringcoinapp/img/twitter.png'
    steemit: '%kernel.project_dir%/web/bundles/ringcoinapp/img/steemit.png'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path:  "%kernel.project_dir%/var/sessions/%kernel.environment%"  #'%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    port: '%mailer_port%'
    encryption: '%mailer_encryption%'
    password: '%mailer_password%'
    spool: { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class:  RingCoin\AppBundle\Entity\User
    service:
      mailer: fos_user.mailer.twig_swift
    from_email:
      address: '%mailer_user%'
      sender_name: RingCorp
    profile:
      form:
        type: RingCoin\AppBundle\Form\ProfileType
        name: ring_app_profile

hwi_oauth:
    connect:
        confirmation: false
        registration_form: fos_user.registration.form.factory
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            google: google_id
            facebook: facebook_id
    resource_owners:
        # Google Access
        google:
            type:                google
            client_id:           77777777777777777777
            client_secret:       44444444444444444
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            options:
                display: popup

        facebook:
            type:                facebook
            client_id:           4444444444444
            client_secret:       1111111111111
            scope:               "email"
            options:
               display: popup

nelmio_api_doc: ~

jms_i18n_routing:
    default_locale: '%locale%'
    locales: [en, fr]
    strategy: prefix
