# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

     #permet de definir les differents encodage des mdp des users
    encoders:
         RingCoin\AppBundle\Entity\User: md5

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundleProviders:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_doc:
            pattern: ^/api/doc
            security: false

        main:
            pattern: ^/
            form_login:
                provider:   fos_userbundleProviders
                login_path: fos_user_security_login
                check-path: fos_user_security_check
                default_target_path: fos_user_profile_show
                csrf_token_generator: security.csrf.token_manager

            oauth:
                resource_owners:
                    google: "/connect/check-google"
                    facebook: "/connect/check-facebook"
                login_path: fos_user_security_login
                failure_path: hwi_oauth_connect
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

            logout:
                path: fos_user_security_logout
                target: homepage
            remember_me:
                secret:     %secret%
            anonymous:  true


    #definition du controle d'acces qui permet de securiser nos URL
    access_control:

          - { path: ^/dashboard, roles: ROLE_ADMIN }
          - { path: /oauth, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }