<?php
/**
 * Created by PhpStorm.
 * User: wilson
 * Date: 31/10/17
 * Time: 19:07
 */

namespace RingCoin\AppBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;

class ProfileType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nivoExperience', ChoiceType::class, array(
                'choices' => array('profileForm.debutant'=>'debutant', 'profileForm.intermediaire'=>'intermediaire', 'profileForm.expert'=>'expert'),
                'label'=>'Nivo d\'experience en cryptomonnaie',
                'choice_translation_domain'=>'RingCoinAppBundle',
                'expanded'=>false,
                'multiple'=>false
            ))
            ->remove('current_password');
    }

    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\ProfileFormType';
    }

    public function getName()
    {
        return $this->getBlockPrefix();
    }

    public function getBlockPrefix()
    {
        return 'ring_app_profile'; // TODO: Change the autogenerated stub
    }
}